#!/bin/sh /etc/rc.common
# Copyright (C) 2014 DataArt

ALLJOYN_ID=com.devicehive.demo.start
DH_SERVER=http://start.cloud.devicehive.com/devicehive-start/rest
#DH_SERVER=ws://start.cloud.devicehive.com/devicehive-start/websocket

START=98

EXTRA_COMMANDS="status"
EXTRA_HELP="
        status  Check the gateway's alive status"

PROG=/usr/bin/DH_alljoyn
PID_F=/tmp/DH_alljoyn.pid

start()
{
	# start daemon (if pid file doesn't exist)
	/usr/bin/wait_inet.sh && \
	start-stop-daemon -q -S -p ${PID_F} -m -a ${PROG} -- --service $ALLJOYN_ID --server $DH_SERVER &
}


stop()
{
	# stop daemon
	start-stop-daemon -q -K -p ${PID_F}

	# cleanup pid file
	rm -f ${PID_F}
}


# alive status: 0 - alive, 1 - dead
status()
{
	[ -f ${PID_F} ] && { ps -p `cat ${PID_F}` > /dev/null 2>&1; }
}
